/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Internal binding contract, checked by the public JavaScript wrapper. */
export const BCRYPT_API_VERSION: number

export const DEFAULT_COST: number

export declare function genSalt(
  round: number,
  version?: string | undefined | null,
  signal?: AbortSignal | undefined | null,
): Promise<string>

export declare function genSaltSync(round: number, version?: string | undefined | null): string

export declare function hash(
  input: string | Uint8Array,
  cost: number | undefined | null,
  salt: string | Uint8Array | undefined | null,
  version: string | undefined | null,
  rejectLongPasswords: boolean,
  signal?: AbortSignal | undefined | null,
): Promise<string>

export declare function hashSync(
  input: string | Uint8Array,
  cost: number | undefined | null,
  salt: string | Uint8Array | undefined | null,
  version: string | undefined | null,
  rejectLongPasswords: boolean,
): string

export declare function verify(
  password: string | Uint8Array,
  hash: string | Uint8Array,
  signal?: AbortSignal | undefined | null,
): Promise<boolean>

export declare function verifySync(input: string | Uint8Array, hash: string | Uint8Array): boolean
