/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface HashOptions {
  salt?: Buffer
  version?: string
  cost?: number
}
export const DEFAULT_COST: number
export function genSaltSync(): Buffer
export function genSalt(signal?: AbortSignal | undefined | null): Promise<Buffer>
export function hashSync(input: string | Buffer, options?: HashOptions | undefined | null): string
export function hash(
  input: string | Buffer,
  options?: HashOptions | undefined | null,
  signal?: AbortSignal | undefined | null,
): Promise<string>
export function verifySync(input: string | Buffer, hash: string | Buffer): boolean
export function verify(
  password: string | Buffer,
  hash: string | Buffer,
  signal?: AbortSignal | undefined | null,
): Promise<boolean>
export namespace Version {
  export const TWO_A: string
  export const TWO_B: string
  export const TWO_Y: string
  export const TWO_X: string
}
