nodeLinker: node-modules

npmRegistryServer: 'https://registry.npmjs.org/'

yarnPath: .yarn/releases/yarn-4.17.1.cjs

npmPreapprovedPackages:
  - oxlint
  - '@oxlint/*'
  - oxfmt
  - '@oxfmt/*'
  - oxc-parser
  - '@oxc-parser/*'
  - '@oxc-project/*'
  - emnapi
  - '@emnapi/*'
  - '@tybys/wasm-util'
