/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function lint(
  fileName: string,
  sourceCode: string | Buffer,
  allRules?: boolean | string | undefined | null,
): Array<string>
export function denolint(dirname: string, configPath: string): boolean
