/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function cut(sentence: string | Buffer, hmm?: boolean | undefined | null): string[]

export declare function cutAll(sentence: string | Buffer): string[]

export declare function cutForSearch(sentence: string | Buffer, hmm?: boolean | undefined | null): string[]

export declare function extract(sentence: string | Buffer, topn: number, allowedPos?: string | undefined | null): Array<Keyword>

export interface Keyword {
  keyword: string
  weight: number
}

export declare function load(): void

export declare function loadDict(dict: Buffer): void

export declare function loadTFIDFDict(dict: Buffer): void

export declare function tag(sentence: string | Buffer, hmm?: boolean | undefined | null): Array<TaggedWord>

export interface TaggedWord {
  tag: string
  word: string
}

