/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const __nodeFs= require('node:fs')
const __nodePath = require('node:path')
const { WASI: __nodeWASI } = require('node:wasi')
const { Worker } = require('node:worker_threads')

const { instantiateNapiModuleSync: __emnapiInstantiateNapiModuleSync } = require('@emnapi/core')
const { getDefaultContext: __emnapiGetDefaultContext } = require('@emnapi/runtime')

const __wasi = new __nodeWASI({
  version: 'preview1',
  env: process.env,
  preopens: {
    '/': '/'
  }
})

const __emnapiContext = __emnapiGetDefaultContext()

const __sharedMemory = new WebAssembly.Memory({
  initial: 1024,
  maximum: 10240,
  shared: true,
})

const { instance: __napiInstance, module: __wasiModule, napiModule: __napiModule } = __emnapiInstantiateNapiModuleSync(__nodeFs.readFileSync(__nodePath.join(__dirname, 'jieba.wasm32-wasi.wasm')), {
  context: __emnapiContext,
  asyncWorkPoolSize: 4,
  wasi: __wasi,
  onCreateWorker() {
    return new Worker(__nodePath.join(__dirname, 'wasi-worker.mjs'), {
      env: process.env,
      execArgv: ['--experimental-wasi-unstable-preview1'],
    })
  },
  overwriteImports(importObject) {
    importObject.env = {
      ...importObject.env,
      ...importObject.napi,
      ...importObject.emnapi,
      memory: __sharedMemory,
    }
    return importObject
  },
  beforeInit({ instance }) {
    __napi_rs_initialize_modules(instance)
  }
})

function __napi_rs_initialize_modules(__napiInstance) {
  __napiInstance.exports['__napi_register__load_0']?.()
  __napiInstance.exports['__napi_register__load_dict_1']?.()
  __napiInstance.exports['__napi_register__cut_2']?.()
  __napiInstance.exports['__napi_register__cut_all_3']?.()
  __napiInstance.exports['__napi_register__cut_for_search_4']?.()
  __napiInstance.exports['__napi_register__TaggedWord_struct_5']?.()
  __napiInstance.exports['__napi_register__tag_6']?.()
  __napiInstance.exports['__napi_register__Keyword_struct_7']?.()
  __napiInstance.exports['__napi_register__extract_8']?.()
  __napiInstance.exports['__napi_register__load_tfidf_dict_9']?.()
}
module.exports.cut = __napiModule.exports.cut,
module.exports.cutAll = __napiModule.exports.cutAll,
module.exports.cutForSearch = __napiModule.exports.cutForSearch,
module.exports.extract = __napiModule.exports.extract,
module.exports.load = __napiModule.exports.load,
module.exports.loadDict = __napiModule.exports.loadDict,
module.exports.loadTFIDFDict = __napiModule.exports.loadTFIDFDict,
module.exports.tag = __napiModule.exports.tag
