/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class ExternalObject<T> {
  readonly '': {
    readonly '': unique symbol
    [K: symbol]: T
  }
}
export const enum Algorithm {
  Argon2d = 0,
  Argon2i = 1,
  Argon2id = 2,
}
export const enum Version {
  V0x10 = 0,
  V0x13 = 1,
}
export interface Options {
  /**
   * Memory size, expressed in kilobytes, between 1 and (2^32)-1.
   * Value is an integer in decimal (1 to 10 digits).
   */
  memoryCost?: number | undefined | null
  /**
   * Number of iterations, between 1 and (2^32)-1.
   * Value is an integer in decimal (1 to 10 digits).
   */
  timeCost?: number | undefined | null
  /**
   * Degree of parallelism, between 1 and 255.
   * Value is an integer in decimal (1 to 3 digits).
   */
  outputLen?: number | undefined | null
  parallelism?: number | undefined | null
  algorithm?: Algorithm | undefined | null
  version?: Version | undefined | null
  secret?: Buffer | undefined | null
}
export function hash(
  password: string | Buffer,
  options?: Options | undefined | null,
  abortSignal?: AbortSignal | undefined | null,
): Promise<string>
export function verify(
  hashed: string | Buffer,
  password: string | Buffer,
  options?: Options | undefined | null,
  abortSignal?: AbortSignal | undefined | null,
): Promise<boolean>
