/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function crc32(input: string | Buffer, initialState?: number | undefined | null): number

export declare function crc32c(input: string | Buffer, initialState?: number | undefined | null): number

