/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function crc32(input: Uint8Array | string, initialState?: number | undefined | null): number

export declare function crc32c(input: Uint8Array | string, initialState?: number | undefined | null): number
